# Generated by Django 5.2.4 on 2025-07-05 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.utilisateur')),
                ('niveau_acces', models.CharField(choices=[('super_admin', 'Super Admin'), ('gestion_contenu', 'Gestion Contenu'), ('gestion_utilisateurs', 'Gestion Utilisateurs')], default='gestion_contenu', max_length=30)),
            ],
            bases=('myapp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.utilisateur')),
                ('departement', models.CharField(max_length=100)),
            ],
            bases=('myapp.utilisateur',),
        ),
        migrations.CreateModel(
            name='ServiceOrganisation',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.utilisateur')),
                ('secteurResponsable', models.CharField(max_length=100)),
            ],
            bases=('myapp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenu')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('info', 'Info'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='proposee', max_length=20)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenu')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('archivee', 'Archivée')], default='en_cours', max_length=20)),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenu')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workflowvalidation')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
